BT: Resetting BTA dm state while sending disable event
Problem: When disable timer fires after waiting for closure
of ACL connections, bta dm disable event is sent. However,
the bta dm state is not reset. This causes, next enable
sequence to return without starting modules.

Error: When controller module is not initialized during enable
sequence and controller module functions are accessed, assert
occurs causing Bluetooth process to crash.

Fix: The disable event must be sent from proper channel by
calling the appropriate callback even in the case of timeout.

CRs-Fixed: 1105610
Change-Id: I866617f1f443c90a0a9ee16a90bafea709e262cd