Update patch set 2
Patch Set 2: Code-Review-1

This applies cleanly as part of the 2019-01 ASB patch set but it breaks compilation here:

system/bt/stack/./avdt/avdt_scb_act.c:424:13: error: expected expression
            uint8_t sdes_type;
            ^
            if (sdes_type == AVDT_RTCP_SDES_CNAME) {
                ^
system/bt/stack/./avdt/avdt_scb_act.c:468:22: error: no member named 'stream_config' in 'tAVDT_SCB'

Patch-set: 2
Reviewer: Gerrit User 18939 <18939@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Code-Review=-1